language: node_js
node_js:
- '4.2'
before_script:
- npm install -g grunt-cli
script: grunt test
deploy:
  provider: npm
  email: jononor@gmail.com
  on:
    tags: true
    repo: noflo/grunt-noflo-browser
  api_key:
    secure: dCn0Pestiqm0v8BZkxfywfC4hhlRU2TU0GkyX7XmBEwBnwijeg5cEi3qvDIolfkQB3rfvT8RM+MfQE3G4cZP76a3FLCLk+Tox+YlwzN+5Pcxi0raDuQ2BToDGQQ3fE6CH9ZZXB+vJhOm7UL6ufCTfZ4UHNd1Ngt0bm0Md961OMc=
